duration="20s"
address=":8080"
[[profils]]
    name="HTTP"
    [[profils.configs]]
        name="SimpleReverse"
        url="http://reverseproxy/bench"
    [[profils.configs]]
        name="Direct"
        url="http://server/bench"
    [[profils.configs]]
        name="Traefik"
        url="http://traefik/bench"
    [[profils.configs]]
        name="HaProxy"
        url="http://haproxy/bench"
    [[profils.configs]]
        name="Envoy"
        url="http://envoy/bench"
[[profils]]
    name="HTTPS"
    [[profils.configs]]
        name="SimpleReverse"
        url="https://reverseproxy/bench"
    [[profils.configs]]
        name="Traefik"
        url="https://traefik/bench"
    [[profils.configs]]
        name="HaProxy"
        url="https://haproxy/bench"
    [[profils.configs]]
        name="Envoy"
        url="https://envoy/bench"
